# Generated by Django 3.1.6 on 2021-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterField(
            model_name='search',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
